In [1]:
# Notebook 02 — Output Normalization v2

# This notebook converts the original 300 × 20 model-output matrix into
# a validated long-format dataset containing 6,000 experimental outputs.

# Main operations:

# - verify source-file integrity;
# - preserve original Excel cell types and number formats;
# - normalize Excel-converted date and time outputs;
# - preserve missing outputs without imputation;
# - attach benchmark and prompt-audit metadata;
# - compare normalized outputs against the Version 1 evaluation dataset;
# - create the input checkpoint for the corrected evaluation engine.

# No evaluation metric is calculated in this notebook.

In [1]:
# Cell 2
from __future__ import annotations

import hashlib
import json
import re
import warnings

from datetime import date, datetime, time
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.styles.numbers import is_date_format
from openpyxl.utils import get_column_letter
from openpyxl.utils.datetime import from_excel

warnings.filterwarnings("ignore")

print("Notebook 02 imports completed successfully.")

Notebook 02 imports completed successfully.

In [2]:
# Cell 3

ROOT = Path.cwd().resolve()

OUTPUT_ROOT = ROOT / "outputs_v2"
CONFIG_PATH = OUTPUT_ROOT / "config_v2.json"

if not CONFIG_PATH.is_file():
    raise FileNotFoundError(
        f"Version 2 configuration was not found:\n{CONFIG_PATH}\n\n"
        "Run Notebook 00 successfully before continuing."
    )

with CONFIG_PATH.open(
    "r",
    encoding="utf-8",
) as file_handle:
    CONFIG = json.load(file_handle)

DATA_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["data"]
)

TABLE_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["tables"]
)

AUDIT_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["audit"]
)

CHECKPOINT_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["checkpoints"]
)

LOG_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["logs"]
)

for directory in [
    TABLE_DIR,
    AUDIT_DIR,
    CHECKPOINT_DIR,
    LOG_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )

MODEL_OUTPUTS_PATH = (
    DATA_DIR
    / CONFIG["SOURCE_FILES"]["model_outputs"]
)

EVALUATION_V1_PATH = (
    DATA_DIR
    / CONFIG["SOURCE_FILES"]["evaluation_dataset_v1"]
)

BENCHMARK_CHECKPOINT_PATH = (
    CHECKPOINT_DIR / "dataset_clean_v2.parquet"
)

PROMPT_AUDIT_PATH = (
    AUDIT_DIR / "Prompt_Validation_Audit_v2.xlsx"
)

MANIFEST_PATH = (
    LOG_DIR / "Source_File_Manifest_v2.xlsx"
)

PROMPT_LABELS = list(
    CONFIG["EXPECTED_PROMPT_LABELS"]
)

print(f"Project root         : {ROOT}")
print(f"Pipeline version     : {CONFIG['PIPELINE_VERSION']}")
print(f"Model outputs        : {MODEL_OUTPUTS_PATH}")
print(f"Benchmark checkpoint : {BENCHMARK_CHECKPOINT_PATH}")
print(f"Prompt audit         : {PROMPT_AUDIT_PATH}")

Project root         : D:\prompt_control_study
Pipeline version     : 2.0
Model outputs        : D:\prompt_control_study\data\model_outputs.xlsx
Benchmark checkpoint : D:\prompt_control_study\outputs_v2\checkpoints\dataset_clean_v2.parquet
Prompt audit         : D:\prompt_control_study\outputs_v2\audit\Prompt_Validation_Audit_v2.xlsx

In [3]:
# Cell 4

ROOT = Path.cwd().resolve()

OUTPUT_ROOT = ROOT / "outputs_v2"
CONFIG_PATH = OUTPUT_ROOT / "config_v2.json"

if not CONFIG_PATH.is_file():
    raise FileNotFoundError(
        f"Version 2 configuration was not found:\n{CONFIG_PATH}\n\n"
        "Run Notebook 00 successfully before continuing."
    )

with CONFIG_PATH.open(
    "r",
    encoding="utf-8",
) as file_handle:
    CONFIG = json.load(file_handle)

DATA_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["data"]
)

TABLE_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["tables"]
)

AUDIT_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["audit"]
)

CHECKPOINT_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["checkpoints"]
)

LOG_DIR = Path(
    CONFIG["OUTPUT_DIRECTORIES"]["logs"]
)

for directory in [
    TABLE_DIR,
    AUDIT_DIR,
    CHECKPOINT_DIR,
    LOG_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )

MODEL_OUTPUTS_PATH = (
    DATA_DIR
    / CONFIG["SOURCE_FILES"]["model_outputs"]
)

EVALUATION_V1_PATH = (
    DATA_DIR
    / CONFIG["SOURCE_FILES"]["evaluation_dataset_v1"]
)

BENCHMARK_CHECKPOINT_PATH = (
    CHECKPOINT_DIR / "dataset_clean_v2.parquet"
)

PROMPT_AUDIT_PATH = (
    AUDIT_DIR / "Prompt_Validation_Audit_v2.xlsx"
)

MANIFEST_PATH = (
    LOG_DIR / "Source_File_Manifest_v2.xlsx"
)

PROMPT_LABELS = list(
    CONFIG["EXPECTED_PROMPT_LABELS"]
)

print(f"Project root         : {ROOT}")
print(f"Pipeline version     : {CONFIG['PIPELINE_VERSION']}")
print(f"Model outputs        : {MODEL_OUTPUTS_PATH}")
print(f"Benchmark checkpoint : {BENCHMARK_CHECKPOINT_PATH}")
print(f"Prompt audit         : {PROMPT_AUDIT_PATH}")

Project root         : D:\prompt_control_study
Pipeline version     : 2.0
Model outputs        : D:\prompt_control_study\data\model_outputs.xlsx
Benchmark checkpoint : D:\prompt_control_study\outputs_v2\checkpoints\dataset_clean_v2.parquet
Prompt audit         : D:\prompt_control_study\outputs_v2\audit\Prompt_Validation_Audit_v2.xlsx

In [43]:
# Cell 5S

# ============================================================
# Notebook 02 normalization corrections
#
# Correction 1:
# Prevent shorter time/date candidates from matching inside
# longer numeric strings, e.g. "9:12" inside "09:12".
#
# Correction 2:
# Reconstruct the displayed Excel form of formatted numeric
# outputs, e.g. 4200 -> "$4,200" or "4,200", based strictly
# on the source cell's number format.
# ============================================================


def find_document_surface_forms(
    candidates: list[str],
    document_text: str,
) -> list[str]:
    text = str(document_text)

    matches = []

    for candidate in candidates:
        # Numeric boundaries prevent a shorter representation
        # from matching inside a longer one.
        #
        # Example:
        # candidate "9:12" must not match inside "09:12".
        pattern = (
            r"(?<![A-Za-z0-9])"
            + re.escape(candidate)
            + r"(?![A-Za-z0-9])"
        )

        for match in re.finditer(
            pattern,
            text,
            flags=re.IGNORECASE,
        ):
            matches.append(
                {
                    "surface": match.group(0),
                    "start": match.start(),
                    "end": match.end(),
                    "length": (
                        match.end()
                        - match.start()
                    ),
                }
            )

    # Prefer the longest match where candidate matches overlap.
    # This removes artificial cases such as:
    # "09:12" and the embedded substring "9:12".
    matches = sorted(
        matches,
        key=lambda item: (
            item["start"],
            -item["length"],
        ),
    )

    nonoverlapping_matches = []

    for candidate_match in matches:
        overlaps_existing = any(
            not (
                candidate_match["end"]
                <= selected_match["start"]
                or
                candidate_match["start"]
                >= selected_match["end"]
            )
            for selected_match
            in nonoverlapping_matches
        )

        if not overlaps_existing:
            nonoverlapping_matches.append(
                candidate_match
            )

    unique_surfaces = []

    for candidate_match in nonoverlapping_matches:
        surface = candidate_match["surface"]

        if surface not in unique_surfaces:
            unique_surfaces.append(surface)

    return unique_surfaces


def plain_numeric_text(
    value: int | float,
) -> str:
    decimal_value = Decimal(str(value))

    if (
        decimal_value
        == decimal_value.to_integral()
    ):
        return format(
            decimal_value.quantize(
                Decimal("1")
            ),
            "f",
        )

    formatted = format(
        decimal_value.normalize(),
        "f",
    )

    if "." in formatted:
        formatted = (
            formatted
            .rstrip("0")
            .rstrip(".")
        )

    return formatted


def extract_excel_literal(
    format_segment: str,
) -> str:
    """
    Extract literal visible characters from a number-format
    segment without reproducing spacing/control instructions.
    """

    visible_parts = []

    # Quoted literals, e.g. "$"
    visible_parts.extend(
        re.findall(
            r'"([^"]*)"',
            format_segment,
        )
    )

    # Escaped literal characters, e.g. \$
    visible_parts.extend(
        re.findall(
            r"\\([^0#?,.;_\-*])",
            format_segment,
        )
    )

    # Unquoted common currency symbols
    for symbol in [
        "$",
        "€",
        "£",
        "¥",
    ]:
        if (
            symbol in format_segment
            and not any(
                symbol in part
                for part in visible_parts
            )
        ):
            visible_parts.append(symbol)

    return "".join(visible_parts)


def format_numeric_value(
    value: int | float,
    number_format: str,
) -> str:
    if isinstance(value, bool):
        return str(value)

    plain_value = plain_numeric_text(value)

    if not isinstance(number_format, str):
        return plain_value

    format_code = number_format.strip()

    if (
        format_code == ""
        or format_code.casefold()
        == "general"
    ):
        return plain_value

    # Use the positive-value format section.
    positive_section = (
        format_code
        .split(";")[0]
        .strip()
    )

    if "%" in positive_section:
        percentage_value = (
            Decimal(str(value))
            * Decimal("100")
        )

        decimal_match = re.search(
            r"\.([0#]+)",
            positive_section,
        )

        decimal_places = (
            len(decimal_match.group(1))
            if decimal_match
            else 0
        )

        return (
            f"{percentage_value:.{decimal_places}f}"
            "%"
        )

    placeholder_positions = [
        position
        for position, character
        in enumerate(positive_section)
        if character in {
            "0",
            "#",
            "?",
        }
    ]

    if not placeholder_positions:
        return plain_value

    first_placeholder = min(
        placeholder_positions
    )

    last_placeholder = max(
        placeholder_positions
    )

    prefix_segment = positive_section[
        :first_placeholder
    ]

    numeric_segment = positive_section[
        first_placeholder:
        last_placeholder + 1
    ]

    suffix_segment = positive_section[
        last_placeholder + 1:
    ]

    prefix = extract_excel_literal(
        prefix_segment
    )

    suffix = extract_excel_literal(
        suffix_segment
    )

    use_thousands_separator = (
        "," in numeric_segment
    )

    decimal_match = re.search(
        r"\.([0#]+)",
        numeric_segment,
    )

    decimal_places = (
        len(decimal_match.group(1))
        if decimal_match
        else 0
    )

    decimal_value = Decimal(
        str(value)
    )

    if use_thousands_separator:
        formatted_number = format(
            decimal_value,
            f",.{decimal_places}f",
        )
    else:
        formatted_number = format(
            decimal_value,
            f".{decimal_places}f",
        )

    if decimal_places == 0:
        formatted_number = (
            formatted_number
            .split(".")[0]
        )

    return (
        f"{prefix}"
        f"{formatted_number}"
        f"{suffix}"
    )


# Keep a reference to the original complete normalizer.
# The guard prevents recursive wrapping if this cell is run again.
if (
    "_base_normalize_model_output_cell"
    not in globals()
):
    _base_normalize_model_output_cell = (
        normalize_model_output_cell
    )


def normalize_model_output_cell(
    *,
    raw_value: Any,
    number_format: str,
    document_text: str,
    workbook_epoch: Any,
) -> dict[str, Any]:
    result = (
        _base_normalize_model_output_cell(
            raw_value=raw_value,
            number_format=number_format,
            document_text=document_text,
            workbook_epoch=workbook_epoch,
        )
    )

    if (
        result[
            "source_value_category"
        ]
        == "numeric"
        and not result["output_missing"]
    ):
        plain_value = plain_numeric_text(
            raw_value
        )

        if result["answer"] != plain_value:
            result[
                "normalization_status"
            ] = (
                "NUMERIC_DISPLAY_RECONSTRUCTED"
            )
        else:
            result[
                "normalization_status"
            ] = (
                "NUMERIC_VALUE_PRESERVED"
            )

    return result


print(
    "Date/time matching and numeric-display "
    "normalization corrections are active."
)

Date/time matching and numeric-display normalization corrections are active.

In [44]:
# Cell 5T

# Time substring-overlap test
time_matches = find_document_surface_forms(
    [
        "09:12",
        "9:12",
        "9:12 AM",
    ],
    "The incident began at 09:12.",
)

print(
    "Time surface matches:",
    time_matches,
)

assert time_matches == [
    "09:12"
]


# Currency-format test
currency_test = format_numeric_value(
    4200,
    '"$"#,##0_);[Red]\\("$"#,##0\\)',
)

print(
    "Currency display:",
    currency_test,
)

assert currency_test == "$4,200"


# Thousands-separator test
grouped_number_test = (
    format_numeric_value(
        4200,
        "#,##0",
    )
)

print(
    "Grouped-number display:",
    grouped_number_test,
)

assert grouped_number_test == "4,200"


# General numeric test
general_number_test = (
    format_numeric_value(
        14,
        "General",
    )
)

print(
    "General numeric display:",
    general_number_test,
)

assert general_number_test == "14"


print(
    "Normalization correction smoke tests passed."
)

Time surface matches: ['09:12']
Currency display: $4,200
Grouped-number display: 4,200
General numeric display: 14
Normalization correction smoke tests passed.

In [4]:
# Cell 5R

import re

from datetime import date, datetime, time
from decimal import Decimal, InvalidOperation
from typing import Any

from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.styles.numbers import is_date_format
from openpyxl.utils import get_column_letter
from openpyxl.utils.datetime import from_excel


MONTH_NAMES_FULL = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

MONTH_NAMES_ABBR = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]


def is_missing_value(value: Any) -> bool:
    if value is None:
        return True

    try:
        result = pd.isna(value)

        if isinstance(result, (bool, np.bool_)):
            return bool(result)

        return False

    except (TypeError, ValueError):
        return False


def normalize_whitespace(value: Any) -> str:
    if is_missing_value(value):
        return ""

    text = str(value)

    text = (
        text
        .replace("_x000D_", "\n")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
    )

    return re.sub(
        r"\s+",
        " ",
        text,
    ).strip()


def canonical_casefold(value: Any) -> str:
    return normalize_whitespace(value).casefold()


def date_surface_candidates(
    value: date | datetime,
) -> list[str]:
    current_date = (
        value.date()
        if isinstance(value, datetime)
        else value
    )

    day = current_date.day
    month_number = current_date.month
    year = current_date.year

    full_month = MONTH_NAMES_FULL[
        month_number - 1
    ]

    short_month = MONTH_NAMES_ABBR[
        month_number - 1
    ]

    candidates = [
        f"{day} {full_month} {year}",
        f"{day} {short_month} {year}",
        f"{full_month} {day}, {year}",
        f"{short_month} {day}, {year}",
        f"{year}-{month_number:02d}-{day:02d}",
        f"{day:02d}/{month_number:02d}/{year}",
        f"{month_number:02d}/{day:02d}/{year}",
        f"{day}/{month_number}/{year}",
        f"{month_number}/{day}/{year}",
    ]

    return list(dict.fromkeys(candidates))


def time_surface_candidates(
    value: time | datetime,
) -> list[str]:
    current_time = (
        value.time()
        if isinstance(value, datetime)
        else value
    )

    hour = current_time.hour
    minute = current_time.minute
    second = current_time.second

    hour_12 = hour % 12 or 12

    am_pm = "AM" if hour < 12 else "PM"

    candidates = [
        f"{hour:02d}:{minute:02d}",
        f"{hour}:{minute:02d}",
        f"{hour_12}:{minute:02d} {am_pm}",
        f"{hour_12}:{minute:02d}{am_pm}",
    ]

    if second != 0:
        candidates.extend(
            [
                f"{hour:02d}:{minute:02d}:{second:02d}",
                f"{hour}:{minute:02d}:{second:02d}",
                (
                    f"{hour_12}:{minute:02d}:"
                    f"{second:02d} {am_pm}"
                ),
            ]
        )

    return list(dict.fromkeys(candidates))


def find_document_surface_forms(
    candidates: list[str],
    document_text: str,
) -> list[str]:
    matches = []

    for candidate in candidates:
        match = re.search(
            re.escape(candidate),
            str(document_text),
            flags=re.IGNORECASE,
        )

        if match:
            matches.append(match.group(0))

    return list(dict.fromkeys(matches))


def canonical_date_text(
    value: date | datetime,
) -> str:
    current_date = (
        value.date()
        if isinstance(value, datetime)
        else value
    )

    return current_date.strftime("%Y-%m-%d")


def canonical_time_text(
    value: time | datetime,
) -> str:
    current_time = (
        value.time()
        if isinstance(value, datetime)
        else value
    )

    if current_time.second:
        return current_time.strftime("%H:%M:%S")

    return current_time.strftime("%H:%M")


def format_numeric_value(
    value: int | float,
    number_format: str,
) -> str:
    if isinstance(value, bool):
        return str(value)

    if (
        isinstance(number_format, str)
        and "%" in number_format
    ):
        percentage_value = (
            Decimal(str(value))
            * Decimal("100")
        )

        percentage_text = format(
            percentage_value.normalize(),
            "f",
        )

        return f"{percentage_text}%"

    try:
        decimal_value = Decimal(str(value))

    except InvalidOperation:
        return str(value)

    if decimal_value == decimal_value.to_integral():
        return format(
            decimal_value.quantize(
                Decimal("1")
            ),
            "f",
        )

    formatted = format(
        decimal_value.normalize(),
        "f",
    )

    if "." in formatted:
        formatted = (
            formatted
            .rstrip("0")
            .rstrip(".")
        )

    return formatted


def parse_model_output_column(
    column_name: str,
) -> tuple[str, str]:
    pattern = re.fullmatch(
        r"(?P<model>.+)_"
        r"(?P<prompt>C1|C2|A|B|C)_output",
        str(column_name),
    )

    if not pattern:
        raise ValueError(
            "Unexpected model-output column name: "
            f"{column_name}"
        )

    return (
        pattern.group("model"),
        pattern.group("prompt"),
    )


def write_table(
    dataframe: pd.DataFrame,
    output_path: Path,
    *,
    sheet_name: str = "Table",
    index: bool = False,
) -> None:
    with pd.ExcelWriter(
        output_path,
        engine="openpyxl",
    ) as writer:
        dataframe.to_excel(
            writer,
            index=index,
            sheet_name=sheet_name,
        )

        worksheet = writer.book[sheet_name]

        header_fill = PatternFill(
            fill_type="solid",
            fgColor="1F4E78",
        )

        header_font = Font(
            color="FFFFFF",
            bold=True,
        )

        for cell in worksheet[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(
                horizontal="center",
                vertical="center",
                wrap_text=True,
            )

        worksheet.freeze_panes = "A2"
        worksheet.auto_filter.ref = worksheet.dimensions

        for column_cells in worksheet.columns:
            column_letter = get_column_letter(
                column_cells[0].column
            )

            max_length = 0

            for cell in column_cells:
                cell.alignment = Alignment(
                    vertical="top",
                    wrap_text=True,
                )

                value_length = len(
                    str(cell.value)
                    if cell.value is not None
                    else ""
                )

                max_length = max(
                    max_length,
                    value_length,
                )

            worksheet.column_dimensions[
                column_letter
            ].width = min(
                max(max_length + 2, 10),
                45,
            )


def normalize_model_output_cell(
    *,
    raw_value: Any,
    number_format: str,
    document_text: str,
    workbook_epoch: Any,
) -> dict[str, Any]:
    value = raw_value
    converted_from_excel_serial = False

    if (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and isinstance(number_format, str)
        and is_date_format(number_format)
    ):
        try:
            value = from_excel(
                value,
                epoch=workbook_epoch,
            )

            converted_from_excel_serial = True

        except (
            TypeError,
            ValueError,
            OverflowError,
        ):
            value = raw_value

    if is_missing_value(value):
        return {
            "answer": "",
            "output_missing": True,
            "source_value_category": "missing",
            "normalization_status": "MISSING_OUTPUT",
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": (
                type(value).__name__
            ),
        }

    if isinstance(value, str):
        normalized_text = normalize_whitespace(value)

        if normalized_text == "":
            return {
                "answer": "",
                "output_missing": True,
                "source_value_category": "blank_string",
                "normalization_status": "BLANK_OUTPUT",
                "document_surface_match": None,
                "surface_match_count": 0,
                "converted_from_excel_serial": (
                    converted_from_excel_serial
                ),
                "normalized_python_type": "str",
            }

        return {
            "answer": normalized_text,
            "output_missing": False,
            "source_value_category": "text",
            "normalization_status": "TEXT_NORMALIZED",
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "str",
        }

    if isinstance(value, datetime):
        is_date_only = (
            value.hour == 0
            and value.minute == 0
            and value.second == 0
            and value.microsecond == 0
        )

        if is_date_only:
            matches = find_document_surface_forms(
                date_surface_candidates(value),
                document_text,
            )

            if len(matches) == 1:
                answer = matches[0]
                status = "DATE_RESOLVED_FROM_DOCUMENT"

            elif len(matches) > 1:
                answer = canonical_date_text(value)
                status = (
                    "DATE_MULTIPLE_DOCUMENT_SURFACES_"
                    "CANONICALIZED"
                )

            else:
                answer = canonical_date_text(value)
                status = (
                    "DATE_NO_DOCUMENT_SURFACE_"
                    "CANONICALIZED"
                )

            return {
                "answer": answer,
                "output_missing": False,
                "source_value_category": "excel_date",
                "normalization_status": status,
                "document_surface_match": len(matches) > 0,
                "surface_match_count": len(matches),
                "converted_from_excel_serial": (
                    converted_from_excel_serial
                ),
                "normalized_python_type": "datetime",
            }

        combined_text = (
            value
            .replace(microsecond=0)
            .isoformat(sep=" ")
        )

        return {
            "answer": combined_text,
            "output_missing": False,
            "source_value_category": "excel_datetime",
            "normalization_status": (
                "DATETIME_CANONICALIZED"
            ),
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "datetime",
        }

    if isinstance(value, date):
        matches = find_document_surface_forms(
            date_surface_candidates(value),
            document_text,
        )

        if len(matches) == 1:
            answer = matches[0]
            status = "DATE_RESOLVED_FROM_DOCUMENT"

        elif len(matches) > 1:
            answer = canonical_date_text(value)
            status = (
                "DATE_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )

        else:
            answer = canonical_date_text(value)
            status = (
                "DATE_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        return {
            "answer": answer,
            "output_missing": False,
            "source_value_category": "excel_date",
            "normalization_status": status,
            "document_surface_match": len(matches) > 0,
            "surface_match_count": len(matches),
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "date",
        }

    if isinstance(value, time):
        matches = find_document_surface_forms(
            time_surface_candidates(value),
            document_text,
        )

        if len(matches) == 1:
            answer = matches[0]
            status = "TIME_RESOLVED_FROM_DOCUMENT"

        elif len(matches) > 1:
            answer = canonical_time_text(value)
            status = (
                "TIME_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )

        else:
            answer = canonical_time_text(value)
            status = (
                "TIME_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        return {
            "answer": answer,
            "output_missing": False,
            "source_value_category": "excel_time",
            "normalization_status": status,
            "document_surface_match": len(matches) > 0,
            "surface_match_count": len(matches),
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "time",
        }

    if (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
    ):
        normalized_number = format_numeric_value(
            value,
            number_format,
        )

        return {
            "answer": normalized_number,
            "output_missing": False,
            "source_value_category": "numeric",
            "normalization_status": (
                "NUMERIC_VALUE_PRESERVED"
            ),
            "document_surface_match": (
                canonical_casefold(normalized_number)
                in canonical_casefold(document_text)
            ),
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": (
                type(value).__name__
            ),
        }

    normalized_other = normalize_whitespace(value)

    return {
        "answer": normalized_other,
        "output_missing": normalized_other == "",
        "source_value_category": "other",
        "normalization_status": (
            "OTHER_VALUE_STRINGIFIED"
        ),
        "document_surface_match": None,
        "surface_match_count": 0,
        "converted_from_excel_serial": (
            converted_from_excel_serial
        ),
        "normalized_python_type": (
            type(value).__name__
        ),
    }


required_functions = [
    "is_missing_value",
    "normalize_whitespace",
    "canonical_casefold",
    "date_surface_candidates",
    "time_surface_candidates",
    "find_document_surface_forms",
    "canonical_date_text",
    "canonical_time_text",
    "format_numeric_value",
    "parse_model_output_column",
    "write_table",
    "normalize_model_output_cell",
]

missing_functions = [
    function_name
    for function_name in required_functions
    if function_name not in globals()
]

if missing_functions:
    raise RuntimeError(
        "Helper-function initialization failed: "
        + ", ".join(missing_functions)
    )

print("All Notebook 02 helper functions are available.")

All Notebook 02 helper functions are available.

In [46]:
# Cell 5

required_paths = [
    MODEL_OUTPUTS_PATH,
    EVALUATION_V1_PATH,
    BENCHMARK_CHECKPOINT_PATH,
    PROMPT_AUDIT_PATH,
    MANIFEST_PATH,
]

missing_required_paths = [
    path
    for path in required_paths
    if not path.is_file()
]

if missing_required_paths:
    raise FileNotFoundError(
        "Required files are missing:\n"
        + "\n".join(
            str(path)
            for path in missing_required_paths
        )
    )


def calculate_sha256(
    file_path: Path,
    chunk_size: int = 1024 * 1024,
) -> str:
    digest = hashlib.sha256()

    with file_path.open("rb") as file_handle:
        for chunk in iter(
            lambda: file_handle.read(chunk_size),
            b"",
        ):
            digest.update(chunk)

    return digest.hexdigest()


manifest = pd.read_excel(
    MANIFEST_PATH,
)

model_manifest_rows = manifest[
    manifest["filename"]
    == MODEL_OUTPUTS_PATH.name
]

if len(model_manifest_rows) != 1:
    raise RuntimeError(
        "model_outputs.xlsx does not have exactly one "
        "entry in the source manifest."
    )

expected_model_output_hash = (
    model_manifest_rows.iloc[0]["sha256"]
)

current_model_output_hash = calculate_sha256(
    MODEL_OUTPUTS_PATH
)

if current_model_output_hash != expected_model_output_hash:
    raise RuntimeError(
        "model_outputs.xlsx differs from the source file "
        "registered in Notebook 00."
    )

print("All required Notebook 02 inputs were found.")
print("model_outputs.xlsx SHA-256 validation passed.")

All required Notebook 02 inputs were found.
model_outputs.xlsx SHA-256 validation passed.

In [5]:
# Cell 6

benchmark = pd.read_parquet(
    BENCHMARK_CHECKPOINT_PATH,
    engine="pyarrow",
)

prompt_audit = pd.read_excel(
    PROMPT_AUDIT_PATH,
)

benchmark["id"] = pd.to_numeric(
    benchmark["id"],
    errors="raise",
).astype(int)

prompt_audit["id"] = pd.to_numeric(
    prompt_audit["id"],
    errors="raise",
).astype(int)

prompt_audit["prompt"] = (
    prompt_audit["prompt"]
    .astype(str)
    .str.strip()
)

prompt_audit["issues"] = (
    prompt_audit["issues"]
    .fillna("")
    .astype(str)
)

if len(benchmark) != CONFIG["EXPECTED_BENCHMARK_ROWS"]:
    raise RuntimeError(
        "Unexpected benchmark checkpoint row count."
    )

if benchmark["id"].nunique() != 300:
    raise RuntimeError(
        "Benchmark checkpoint IDs are not unique."
    )

if len(prompt_audit) != 1500:
    raise RuntimeError(
        "Prompt audit does not contain 1,500 rows."
    )

prompt_issue_map = {
    (
        int(row["id"]),
        str(row["prompt"]),
    ): str(row["issues"])
    for _, row in prompt_audit.iterrows()
}

benchmark_by_id = (
    benchmark
    .set_index("id")
    .sort_index()
)

print(f"Benchmark rows   : {len(benchmark)}")
print(f"Prompt audit rows: {len(prompt_audit)}")
print("Notebook 01 checkpoints loaded successfully.")

Benchmark rows   : 300
Prompt audit rows: 1500
Notebook 01 checkpoints loaded successfully.

In [48]:
def parse_model_output_column(
    column_name: str,
) -> tuple[str, str]:
    pattern = re.fullmatch(
        r"(?P<model>.+)_"
        r"(?P<prompt>C1|C2|A|B|C)_output",
        str(column_name),
    )

    if not pattern:
        raise ValueError(
            "Unexpected model-output column name: "
            f"{column_name}"
        )

    return (
        pattern.group("model"),
        pattern.group("prompt"),
    )


print("parse_model_output_column is available.")

parse_model_output_column is available.

In [6]:
# Cell 7

model_output_workbook = load_workbook(
    MODEL_OUTPUTS_PATH,
    data_only=True,
    read_only=False,
)

model_output_sheet = model_output_workbook.active


# ------------------------------------------------------------
# Detect actual data rows using the ID column.
# This avoids relying only on worksheet.max_row, which may
# include formatted but empty rows.
# ------------------------------------------------------------

DATA_ROW_INDICES = [
    row_index
    for row_index in range(
        2,
        model_output_sheet.max_row + 1,
    )
    if model_output_sheet.cell(
        row=row_index,
        column=1,
    ).value is not None
]

if len(DATA_ROW_INDICES) != 300:
    raise RuntimeError(
        "model_outputs.xlsx must contain exactly "
        f"300 nonempty ID rows; found {len(DATA_ROW_INDICES)}."
    )

expected_data_rows = list(
    range(
        2,
        302,
    )
)

if DATA_ROW_INDICES != expected_data_rows:
    raise RuntimeError(
        "The 300 model-output rows are not stored "
        "contiguously in Excel rows 2 through 301."
    )

LAST_DATA_ROW = max(DATA_ROW_INDICES)


# ------------------------------------------------------------
# Read all physically registered worksheet headers.
# Excel/openpyxl may report an extra formatted but empty column.
# ------------------------------------------------------------

physical_headers = [
    model_output_sheet.cell(
        row=1,
        column=column_index,
    ).value
    for column_index in range(
        1,
        model_output_sheet.max_column + 1,
    )
]

nonempty_header_indices = [
    column_index
    for column_index, header_value in enumerate(
        physical_headers,
        start=1,
    )
    if header_value is not None
    and str(header_value).strip() != ""
]

if not nonempty_header_indices:
    raise RuntimeError(
        "No nonempty headers were found in model_outputs.xlsx."
    )

LAST_DATA_COLUMN = max(
    nonempty_header_indices
)

output_headers = [
    model_output_sheet.cell(
        row=1,
        column=column_index,
    ).value
    for column_index in range(
        1,
        LAST_DATA_COLUMN + 1,
    )
]


# ------------------------------------------------------------
# Validate that blank columns do not occur inside the actual
# data range.
# ------------------------------------------------------------

internal_blank_headers = [
    column_index
    for column_index, header_value in enumerate(
        output_headers,
        start=1,
    )
    if header_value is None
    or str(header_value).strip() == ""
]

if internal_blank_headers:
    raise RuntimeError(
        "Blank header columns were found inside the actual "
        f"data range: {internal_blank_headers}"
    )


# ------------------------------------------------------------
# Any columns after the final real header must be entirely empty.
# In the current source file, column 22 is a trailing empty
# worksheet column and is safely ignored.
# ------------------------------------------------------------

trailing_nonempty_cells = []

for column_index in range(
    LAST_DATA_COLUMN + 1,
    model_output_sheet.max_column + 1,
):
    for row_index in range(
        1,
        LAST_DATA_ROW + 1,
    ):
        cell_value = model_output_sheet.cell(
            row=row_index,
            column=column_index,
        ).value

        if cell_value is not None:
            trailing_nonempty_cells.append(
                {
                    "row": row_index,
                    "column": column_index,
                    "value": cell_value,
                }
            )

if trailing_nonempty_cells:
    display(
        pd.DataFrame(
            trailing_nonempty_cells
        )
    )

    raise RuntimeError(
        "Nonempty cells were found after the final "
        "recognized output column."
    )


# ------------------------------------------------------------
# Validate expected logical structure.
# ------------------------------------------------------------

if output_headers[0] != "id":
    raise ValueError(
        "The first model-output column must be 'id'."
    )

if len(output_headers) != 21:
    raise RuntimeError(
        "The logical model-output table must contain "
        "21 populated columns: one ID column and "
        f"20 output columns. Found {len(output_headers)}."
    )


output_column_specs = []

for column_index, column_name in enumerate(
    output_headers[1:],
    start=2,
):
    model_name, prompt_label = (
        parse_model_output_column(
            str(column_name)
        )
    )

    output_column_specs.append(
        {
            "column_index": column_index,
            "column_name": str(column_name),
            "model": model_name,
            "prompt": prompt_label,
        }
    )


output_column_specification = pd.DataFrame(
    output_column_specs
)

detected_models = sorted(
    output_column_specification[
        "model"
    ].unique()
)

detected_prompts = sorted(
    output_column_specification[
        "prompt"
    ].unique()
)

display(
    output_column_specification
)

print(
    f"Worksheet physical rows   : "
    f"{model_output_sheet.max_row}"
)

print(
    f"Worksheet physical columns: "
    f"{model_output_sheet.max_column}"
)

print(
    f"Actual data rows          : "
    f"{len(DATA_ROW_INDICES)}"
)

print(
    f"Actual populated columns  : "
    f"{len(output_headers)}"
)

print(
    f"Trailing empty columns    : "
    f"{model_output_sheet.max_column - LAST_DATA_COLUMN}"
)

print(
    f"Detected models           : "
    f"{len(detected_models)}"
)

print(
    f"Detected prompts          : "
    f"{detected_prompts}"
)

if len(detected_models) != CONFIG["EXPECTED_MODEL_COUNT"]:
    raise RuntimeError(
        "Unexpected number of models."
    )

if set(detected_prompts) != set(PROMPT_LABELS):
    raise RuntimeError(
        "Unexpected Prompt labels."
    )

print("Raw output matrix structure validated.")

    column_index                  column_name              model prompt
0              2             gpt 5.4_A_output            gpt 5.4      A
1              3             gpt 5.4_B_output            gpt 5.4      B
2              4             gpt 5.4_C_output            gpt 5.4      C
3              5            gpt 5.4_C1_output            gpt 5.4     C1
4              6            gpt 5.4_C2_output            gpt 5.4     C2
5              7   claude 4.6 Sonnet_A_output  claude 4.6 Sonnet      A
6              8   claude 4.6 Sonnet_B_output  claude 4.6 Sonnet      B
7              9   claude 4.6 Sonnet_C_output  claude 4.6 Sonnet      C
8             10  claude 4.6 Sonnet_C1_output  claude 4.6 Sonnet     C1
9             11  claude 4.6 Sonnet_C2_output  claude 4.6 Sonnet     C2
10            12      Gemini 3.1 Pro_A_output     Gemini 3.1 Pro      A
11            13      Gemini 3.1 Pro_B_output     Gemini 3.1 Pro      B
12            14      Gemini 3.1 Pro_C_output     Gemini 3.1 Pro      C
13            15     Gemini 3.1 Pro_C1_output     Gemini 3.1 Pro     C1
14            16     Gemini 3.1 Pro_C2_output     Gemini 3.1 Pro     C2
15            17     DeepSeek V4 Pro_A_output    DeepSeek V4 Pro      A
16            18     DeepSeek V4 Pro_B_output    DeepSeek V4 Pro      B
17            19     DeepSeek V4 Pro_C_output    DeepSeek V4 Pro      C
18            20    DeepSeek V4 Pro_C1_output    DeepSeek V4 Pro     C1
19            21    DeepSeek V4 Pro_C2_output    DeepSeek V4 Pro     C2

Worksheet physical rows   : 301
Worksheet physical columns: 22
Actual data rows          : 300
Actual populated columns  : 21
Trailing empty columns    : 1
Detected models           : 4
Detected prompts          : ['A', 'B', 'C', 'C1', 'C2']
Raw output matrix structure validated.

In [7]:
# Cell 8F

from datetime import datetime, time
from decimal import Decimal
from typing import Any

from openpyxl.styles.numbers import is_date_format
from openpyxl.utils.datetime import from_excel


NORMALIZATION_PATCH_VERSION = "2.1.0-final"


def strict_document_surface_matches(
    candidates: list[str],
    document_text: str,
) -> list[str]:
    """
    Find non-overlapping document surface forms.

    Numeric boundaries prevent a shorter candidate such as
    '9:12' from matching inside '09:12'.
    """

    document = str(document_text)
    raw_matches = []

    for candidate in candidates:
        pattern = (
            r"(?<![A-Za-z0-9])"
            + re.escape(candidate)
            + r"(?![A-Za-z0-9])"
        )

        for match in re.finditer(
            pattern,
            document,
            flags=re.IGNORECASE,
        ):
            raw_matches.append(
                {
                    "surface": match.group(0),
                    "start": match.start(),
                    "end": match.end(),
                    "length": (
                        match.end()
                        - match.start()
                    ),
                }
            )

    # For overlapping candidates, retain the longest one.
    raw_matches = sorted(
        raw_matches,
        key=lambda item: (
            item["start"],
            -item["length"],
        ),
    )

    selected_matches = []

    for candidate_match in raw_matches:
        overlaps = any(
            not (
                candidate_match["end"]
                <= selected_match["start"]
                or
                candidate_match["start"]
                >= selected_match["end"]
            )
            for selected_match in selected_matches
        )

        if not overlaps:
            selected_matches.append(
                candidate_match
            )

    unique_surfaces = []

    for selected_match in selected_matches:
        surface = selected_match["surface"]

        if surface not in unique_surfaces:
            unique_surfaces.append(surface)

    return unique_surfaces


def plain_numeric_text(
    value: int | float,
) -> str:
    decimal_value = Decimal(str(value))

    if (
        decimal_value
        == decimal_value.to_integral()
    ):
        return format(
            decimal_value.quantize(
                Decimal("1")
            ),
            "f",
        )

    result = format(
        decimal_value.normalize(),
        "f",
    )

    if "." in result:
        result = (
            result
            .rstrip("0")
            .rstrip(".")
        )

    return result


def extract_visible_excel_literal(
    format_segment: str,
) -> str:
    visible_parts = []

    # Quoted literals such as "$"
    visible_parts.extend(
        re.findall(
            r'"([^"]*)"',
            format_segment,
        )
    )

    # Escaped literal characters
    visible_parts.extend(
        re.findall(
            r"\\([^0#?,.;_\-*])",
            format_segment,
        )
    )

    for symbol in [
        "$",
        "€",
        "£",
        "¥",
    ]:
        if (
            symbol in format_segment
            and not any(
                symbol in part
                for part in visible_parts
            )
        ):
            visible_parts.append(symbol)

    return "".join(visible_parts)


def reconstruct_numeric_display(
    value: int | float,
    number_format: str,
) -> str:
    """
    Reconstruct the visible Excel representation strictly from
    the stored numeric value and the cell number format.
    """

    plain_value = plain_numeric_text(value)

    if not isinstance(number_format, str):
        return plain_value

    format_code = number_format.strip()

    if (
        format_code == ""
        or format_code.casefold() == "general"
    ):
        return plain_value

    positive_section = (
        format_code
        .split(";")[0]
        .strip()
    )

    if "%" in positive_section:
        percentage_value = (
            Decimal(str(value))
            * Decimal("100")
        )

        decimal_match = re.search(
            r"\.([0#]+)",
            positive_section,
        )

        decimal_places = (
            len(decimal_match.group(1))
            if decimal_match
            else 0
        )

        return (
            f"{percentage_value:.{decimal_places}f}"
            "%"
        )

    placeholder_positions = [
        position
        for position, character
        in enumerate(positive_section)
        if character in {
            "0",
            "#",
            "?",
        }
    ]

    if not placeholder_positions:
        return plain_value

    first_placeholder = min(
        placeholder_positions
    )

    last_placeholder = max(
        placeholder_positions
    )

    prefix_segment = positive_section[
        :first_placeholder
    ]

    numeric_segment = positive_section[
        first_placeholder:
        last_placeholder + 1
    ]

    suffix_segment = positive_section[
        last_placeholder + 1:
    ]

    prefix = extract_visible_excel_literal(
        prefix_segment
    )

    suffix = extract_visible_excel_literal(
        suffix_segment
    )

    use_grouping = "," in numeric_segment

    decimal_match = re.search(
        r"\.([0#]+)",
        numeric_segment,
    )

    decimal_places = (
        len(decimal_match.group(1))
        if decimal_match
        else 0
    )

    decimal_value = Decimal(str(value))

    if use_grouping:
        formatted_number = format(
            decimal_value,
            f",.{decimal_places}f",
        )
    else:
        formatted_number = format(
            decimal_value,
            f".{decimal_places}f",
        )

    if decimal_places == 0:
        formatted_number = (
            formatted_number
            .split(".")[0]
        )

    return (
        f"{prefix}"
        f"{formatted_number}"
        f"{suffix}"
    )


# Obtain the original normalizer even when this Patch cell
# is accidentally executed more than once.
_base_normalizer = getattr(
    normalize_model_output_cell,
    "_base_normalizer",
    normalize_model_output_cell,
)


def normalize_model_output_cell_final(
    *,
    raw_value: Any,
    number_format: str,
    document_text: str,
    workbook_epoch: Any,
) -> dict[str, Any]:
    result = _base_normalizer(
        raw_value=raw_value,
        number_format=number_format,
        document_text=document_text,
        workbook_epoch=workbook_epoch,
    )

    # --------------------------------------------------------
    # Correct time normalization
    # --------------------------------------------------------

    if (
        result["source_value_category"]
        == "excel_time"
    ):
        time_value = raw_value

        if (
            isinstance(
                time_value,
                (int, float),
            )
            and not isinstance(
                time_value,
                bool,
            )
            and isinstance(
                number_format,
                str,
            )
            and is_date_format(
                number_format
            )
        ):
            time_value = from_excel(
                time_value,
                epoch=workbook_epoch,
            )

        if isinstance(
            time_value,
            datetime,
        ):
            time_value = time_value.time()

        if not isinstance(
            time_value,
            time,
        ):
            raise TypeError(
                "An Excel time output could not be "
                "recovered as a Python time value."
            )

        matches = (
            strict_document_surface_matches(
                time_surface_candidates(
                    time_value
                ),
                document_text,
            )
        )

        if len(matches) == 1:
            result["answer"] = matches[0]
            result["normalization_status"] = (
                "TIME_RESOLVED_FROM_DOCUMENT"
            )

        elif len(matches) > 1:
            result["answer"] = (
                canonical_time_text(
                    time_value
                )
            )

            result["normalization_status"] = (
                "TIME_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )

        else:
            result["answer"] = (
                canonical_time_text(
                    time_value
                )
            )

            result["normalization_status"] = (
                "TIME_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        result["document_surface_match"] = (
            len(matches) > 0
        )

        result["surface_match_count"] = (
            len(matches)
        )

    # --------------------------------------------------------
    # Correct numeric display reconstruction
    # --------------------------------------------------------

    elif (
        result["source_value_category"]
        == "numeric"
    ):
        reconstructed_answer = (
            reconstruct_numeric_display(
                raw_value,
                number_format,
            )
        )

        unformatted_answer = (
            plain_numeric_text(
                raw_value
            )
        )

        result["answer"] = (
            reconstructed_answer
        )

        result["document_surface_match"] = (
            canonical_casefold(
                reconstructed_answer
            )
            in canonical_casefold(
                document_text
            )
        )

        if (
            reconstructed_answer
            != unformatted_answer
        ):
            result["normalization_status"] = (
                "NUMERIC_DISPLAY_RECONSTRUCTED"
            )
        else:
            result["normalization_status"] = (
                "NUMERIC_VALUE_PRESERVED"
            )

    return result


normalize_model_output_cell_final._base_normalizer = (
    _base_normalizer
)

normalize_model_output_cell_final._patch_version = (
    NORMALIZATION_PATCH_VERSION
)

normalize_model_output_cell = (
    normalize_model_output_cell_final
)


print(
    "Final normalization Patch active:",
    normalize_model_output_cell._patch_version,
)

Final normalization Patch active: 2.1.0-final

In [8]:
# Cell 8G

time_test = normalize_model_output_cell(
    raw_value=time(9, 12),
    number_format="h:mm",
    document_text=(
        "The incident began at 09:12 "
        "on 18 March 2024."
    ),
    workbook_epoch=(
        model_output_workbook.epoch
    ),
)

currency_test = (
    normalize_model_output_cell(
        raw_value=4200,
        number_format=(
            '"$"#,##0_);'
            '[Red]\\("$"#,##0\\)'
        ),
        document_text=(
            "The approved budget was $4,200."
        ),
        workbook_epoch=(
            model_output_workbook.epoch
        ),
    )
)

grouped_number_test = (
    normalize_model_output_cell(
        raw_value=4200,
        number_format="#,##0",
        document_text=(
            "The approved amount was 4,200."
        ),
        workbook_epoch=(
            model_output_workbook.epoch
        ),
    )
)


print("Time test:")
print(time_test)

print("\nCurrency test:")
print(currency_test)

print("\nGrouped-number test:")
print(grouped_number_test)


assert (
    time_test["answer"]
    == "09:12"
)

assert (
    time_test["surface_match_count"]
    == 1
)

assert (
    time_test[
        "normalization_status"
    ]
    == "TIME_RESOLVED_FROM_DOCUMENT"
)

assert (
    currency_test["answer"]
    == "$4,200"
)

assert (
    currency_test[
        "normalization_status"
    ]
    == "NUMERIC_DISPLAY_RECONSTRUCTED"
)

assert (
    grouped_number_test["answer"]
    == "4,200"
)

assert (
    grouped_number_test[
        "normalization_status"
    ]
    == "NUMERIC_DISPLAY_RECONSTRUCTED"
)

print(
    "\nFinal normalization smoke tests passed."
)

Time test:
{'answer': '09:12', 'output_missing': False, 'source_value_category': 'excel_time', 'normalization_status': 'TIME_RESOLVED_FROM_DOCUMENT', 'document_surface_match': True, 'surface_match_count': 1, 'converted_from_excel_serial': False, 'normalized_python_type': 'time'}

Currency test:
{'answer': '$4,200', 'output_missing': False, 'source_value_category': 'numeric', 'normalization_status': 'NUMERIC_DISPLAY_RECONSTRUCTED', 'document_surface_match': True, 'surface_match_count': 0, 'converted_from_excel_serial': False, 'normalized_python_type': 'int'}

Grouped-number test:
{'answer': '4,200', 'output_missing': False, 'source_value_category': 'numeric', 'normalization_status': 'NUMERIC_DISPLAY_RECONSTRUCTED', 'document_surface_match': True, 'surface_match_count': 0, 'converted_from_excel_serial': False, 'normalized_python_type': 'int'}

Final normalization smoke tests passed.

In [50]:
# Cell 8

def normalize_model_output_cell(
    *,
    raw_value: Any,
    number_format: str,
    document_text: str,
    workbook_epoch: Any,
) -> dict[str, Any]:
    original_python_type = (
        type(raw_value).__name__
    )

    value = raw_value
    converted_from_excel_serial = False

    if (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and isinstance(number_format, str)
        and is_date_format(number_format)
    ):
        try:
            value = from_excel(
                value,
                epoch=workbook_epoch,
            )

            converted_from_excel_serial = True
        except (TypeError, ValueError, OverflowError):
            value = raw_value

    if is_missing_value(value):
        return {
            "answer": "",
            "output_missing": True,
            "source_value_category": "missing",
            "normalization_status": "MISSING_OUTPUT",
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": (
                type(value).__name__
            ),
        }

    if isinstance(value, str):
        normalized_text = normalize_whitespace(
            value
        )

        if normalized_text == "":
            return {
                "answer": "",
                "output_missing": True,
                "source_value_category": "blank_string",
                "normalization_status": "BLANK_OUTPUT",
                "document_surface_match": None,
                "surface_match_count": 0,
                "converted_from_excel_serial": (
                    converted_from_excel_serial
                ),
                "normalized_python_type": "str",
            }

        return {
            "answer": normalized_text,
            "output_missing": False,
            "source_value_category": "text",
            "normalization_status": "TEXT_NORMALIZED",
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "str",
        }

    if isinstance(value, datetime):
        is_date_only = (
            value.hour == 0
            and value.minute == 0
            and value.second == 0
            and value.microsecond == 0
        )

        if is_date_only:
            matches = find_document_surface_forms(
                date_surface_candidates(value),
                document_text,
            )

            if len(matches) == 1:
                answer = matches[0]
                status = "DATE_RESOLVED_FROM_DOCUMENT"
            elif len(matches) > 1:
                answer = canonical_date_text(
                    value
                )
                status = (
                    "DATE_MULTIPLE_DOCUMENT_SURFACES_"
                    "CANONICALIZED"
                )
            else:
                answer = canonical_date_text(
                    value
                )
                status = (
                    "DATE_NO_DOCUMENT_SURFACE_"
                    "CANONICALIZED"
                )

            return {
                "answer": answer,
                "output_missing": False,
                "source_value_category": "excel_date",
                "normalization_status": status,
                "document_surface_match": (
                    len(matches) > 0
                ),
                "surface_match_count": len(matches),
                "converted_from_excel_serial": (
                    converted_from_excel_serial
                ),
                "normalized_python_type": "datetime",
            }

        combined_text = (
            value
            .replace(microsecond=0)
            .isoformat(sep=" ")
        )

        return {
            "answer": combined_text,
            "output_missing": False,
            "source_value_category": "excel_datetime",
            "normalization_status": (
                "DATETIME_CANONICALIZED"
            ),
            "document_surface_match": None,
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "datetime",
        }

    if isinstance(value, date):
        matches = find_document_surface_forms(
            date_surface_candidates(value),
            document_text,
        )

        if len(matches) == 1:
            answer = matches[0]
            status = "DATE_RESOLVED_FROM_DOCUMENT"
        elif len(matches) > 1:
            answer = canonical_date_text(
                value
            )
            status = (
                "DATE_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )
        else:
            answer = canonical_date_text(
                value
            )
            status = (
                "DATE_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        return {
            "answer": answer,
            "output_missing": False,
            "source_value_category": "excel_date",
            "normalization_status": status,
            "document_surface_match": (
                len(matches) > 0
            ),
            "surface_match_count": len(matches),
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "date",
        }

    if isinstance(value, time):
        matches = find_document_surface_forms(
            time_surface_candidates(value),
            document_text,
        )

        if len(matches) == 1:
            answer = matches[0]
            status = "TIME_RESOLVED_FROM_DOCUMENT"
        elif len(matches) > 1:
            answer = canonical_time_text(
                value
            )
            status = (
                "TIME_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )
        else:
            answer = canonical_time_text(
                value
            )
            status = (
                "TIME_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        return {
            "answer": answer,
            "output_missing": False,
            "source_value_category": "excel_time",
            "normalization_status": status,
            "document_surface_match": (
                len(matches) > 0
            ),
            "surface_match_count": len(matches),
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": "time",
        }

    if (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
    ):
        normalized_number = format_numeric_value(
            value,
            number_format,
        )

        return {
            "answer": normalized_number,
            "output_missing": False,
            "source_value_category": "numeric",
            "normalization_status": (
                "NUMERIC_VALUE_PRESERVED"
            ),
            "document_surface_match": (
                canonical_casefold(
                    normalized_number
                )
                in canonical_casefold(
                    document_text
                )
            ),
            "surface_match_count": 0,
            "converted_from_excel_serial": (
                converted_from_excel_serial
            ),
            "normalized_python_type": (
                type(value).__name__
            ),
        }

    normalized_other = normalize_whitespace(
        value
    )

    return {
        "answer": normalized_other,
        "output_missing": (
            normalized_other == ""
        ),
        "source_value_category": "other",
        "normalization_status": (
            "OTHER_VALUE_STRINGIFIED"
        ),
        "document_surface_match": None,
        "surface_match_count": 0,
        "converted_from_excel_serial": (
            converted_from_excel_serial
        ),
        "normalized_python_type": (
            type(value).__name__
        ),
    }


print("Output normalization function defined.")

Output normalization function defined.

In [9]:
# Cell 9

assert (
    globals().get(
        "NORMALIZATION_PATCH_VERSION"
    )
    == "2.1.0-final"
), (
    "The final normalization Patch "
    "has not been activated."
)

assert (
    getattr(
        normalize_model_output_cell,
        "_patch_version",
        None,
    )
    == "2.1.0-final"
), (
    "Cell 9 is using an outdated "
    "normalization function."
)

print(
    "Cell 9 normalization Patch:",
    normalize_model_output_cell._patch_version,
)

normalized_output_rows = []

for excel_row_index in DATA_ROW_INDICES:
    
 normalized_output_rows = []

for excel_row_index in range(
    2,
    model_output_sheet.max_row + 1,
):
    id_cell = model_output_sheet.cell(
        row=excel_row_index,
        column=1,
    )

    sample_id = int(
        id_cell.value
    )

    if sample_id not in benchmark_by_id.index:
        raise KeyError(
            f"Sample ID {sample_id} was not found "
            "in the clean benchmark checkpoint."
        )

    benchmark_row = benchmark_by_id.loc[
        sample_id
    ]

    for specification in output_column_specs:
        output_cell = model_output_sheet.cell(
            row=excel_row_index,
            column=specification[
                "column_index"
            ],
        )

        raw_value = output_cell.value

        number_format = (
            output_cell.number_format
            if output_cell.number_format
            else "General"
        )

        normalized_result = (
            normalize_model_output_cell(
                raw_value=raw_value,
                number_format=number_format,
                document_text=benchmark_row[
                    "document_text"
                ],
                workbook_epoch=(
                    model_output_workbook.epoch
                ),
            )
        )

        model_name = specification["model"]
        prompt_label = specification["prompt"]

        experiment_key = (
            f"{sample_id}|"
            f"{model_name}|"
            f"{prompt_label}"
        )

        normalized_output_rows.append(
            {
                "experiment_key": experiment_key,
                "id": sample_id,
                "doc_id": benchmark_row["doc_id"],
                "model": model_name,
                "prompt": prompt_label,
                "document_text": (
                    benchmark_row[
                        "document_text"
                    ]
                ),
                "question": (
                    benchmark_row["question"]
                ),
                "gold_answer": (
                    benchmark_row[
                        "gold_answer"
                    ]
                ),
                "answer": (
                    normalized_result["answer"]
                ),
                "answer_type": (
                    benchmark_row[
                        "answer_type"
                    ]
                ),
                "injection_tag": (
                    benchmark_row[
                        "injection_tag"
                    ]
                ),
                "output_missing": (
                    normalized_result[
                        "output_missing"
                    ]
                ),
                "source_value_category": (
                    normalized_result[
                        "source_value_category"
                    ]
                ),
                "normalization_status": (
                    normalized_result[
                        "normalization_status"
                    ]
                ),
                "document_surface_match": (
                    normalized_result[
                        "document_surface_match"
                    ]
                ),
                "surface_match_count": (
                    normalized_result[
                        "surface_match_count"
                    ]
                ),
                "source_python_type": (
                    type(raw_value).__name__
                ),
                "normalized_python_type": (
                    normalized_result[
                        "normalized_python_type"
                    ]
                ),
                "source_excel_data_type": (
                    output_cell.data_type
                ),
                "source_number_format": (
                    number_format
                ),
                "converted_from_excel_serial": (
                    normalized_result[
                        "converted_from_excel_serial"
                    ]
                ),
                "raw_value_repr": repr(
                    raw_value
                ),
                "source_column": (
                    specification[
                        "column_name"
                    ]
                ),
                "prompt_audit_issue": (
                    prompt_issue_map.get(
                        (
                            sample_id,
                            prompt_label,
                        ),
                        "",
                    )
                ),
            }
        )

model_output_workbook.close()

normalized_outputs = pd.DataFrame(
    normalized_output_rows
)

normalized_outputs = (
    normalized_outputs
    .sort_values(
        [
            "id",
            "model",
            "prompt",
        ]
    )
    .reset_index(drop=True)
)

print(
    f"Normalized experimental rows: "
    f"{len(normalized_outputs)}"
)

display(
    normalized_outputs.head(10)
)

Cell 9 normalization Patch: 2.1.0-final
Normalized experimental rows: 6000

,experiment_key,id,doc_id,model,prompt,document_text,question,gold_answer,answer,answer_type,...,document_surface_match,surface_match_count,source_python_type,normalized_python_type,source_excel_data_type,source_number_format,converted_from_excel_serial,raw_value_repr,source_column,prompt_audit_issue
0,1|DeepSeek V4 Pro|A,1,D01,DeepSeek V4 Pro,A,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,The primary air filter was replaced on 12 Marc...,extractive,...,None,0,str,str,s,General,False,'The primary air filter was replaced on 12 Mar...,DeepSeek V4 Pro_A_output,
1,1|DeepSeek V4 Pro|B,1,D01,DeepSeek V4 Pro,B,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",DeepSeek V4 Pro_B_output,
2,1|DeepSeek V4 Pro|C,1,D01,DeepSeek V4 Pro,C,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024.,extractive,...,None,0,str,str,s,General,False,'12 March 2024.',DeepSeek V4 Pro_C_output,
3,1|DeepSeek V4 Pro|C1,1,D01,DeepSeek V4 Pro,C1,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",DeepSeek V4 Pro_C1_output,
4,1|DeepSeek V4 Pro|C2,1,D01,DeepSeek V4 Pro,C2,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",DeepSeek V4 Pro_C2_output,
5,1|Gemini 3.1 Pro|A,1,D01,Gemini 3.1 Pro,A,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,The primary air filter was replaced on 12 Marc...,extractive,...,None,0,str,str,s,General,False,'The primary air filter was replaced on 12 Mar...,Gemini 3.1 Pro_A_output,
6,1|Gemini 3.1 Pro|B,1,D01,Gemini 3.1 Pro,B,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",Gemini 3.1 Pro_B_output,
7,1|Gemini 3.1 Pro|C,1,D01,Gemini 3.1 Pro,C,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",Gemini 3.1 Pro_C_output,
8,1|Gemini 3.1 Pro|C1,1,D01,Gemini 3.1 Pro,C1,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",Gemini 3.1 Pro_C1_output,
9,1|Gemini 3.1 Pro|C2,1,D01,Gemini 3.1 Pro,C2,The following report summarizes the routine ma...,When was the primary air filter replaced?,12 March 2024,12 March 2024,extractive,...,True,1,datetime,datetime,d,d-mmm-yy,False,"datetime.datetime(2024, 3, 12, 0, 0)",Gemini 3.1 Pro_C2_output,

In [60]:
#Cell 8F

from datetime import datetime, time
from decimal import Decimal
from typing import Any

from openpyxl.styles.numbers import is_date_format
from openpyxl.utils.datetime import from_excel


NORMALIZATION_PATCH_VERSION = "2.1.0-final"


def strict_document_surface_matches(
    candidates: list[str],
    document_text: str,
) -> list[str]:
    """
    Find non-overlapping document surface forms.

    Numeric boundaries prevent a shorter candidate such as
    '9:12' from matching inside '09:12'.
    """

    document = str(document_text)
    raw_matches = []

    for candidate in candidates:
        pattern = (
            r"(?<![A-Za-z0-9])"
            + re.escape(candidate)
            + r"(?![A-Za-z0-9])"
        )

        for match in re.finditer(
            pattern,
            document,
            flags=re.IGNORECASE,
        ):
            raw_matches.append(
                {
                    "surface": match.group(0),
                    "start": match.start(),
                    "end": match.end(),
                    "length": (
                        match.end()
                        - match.start()
                    ),
                }
            )

    # For overlapping candidates, retain the longest one.
    raw_matches = sorted(
        raw_matches,
        key=lambda item: (
            item["start"],
            -item["length"],
        ),
    )

    selected_matches = []

    for candidate_match in raw_matches:
        overlaps = any(
            not (
                candidate_match["end"]
                <= selected_match["start"]
                or
                candidate_match["start"]
                >= selected_match["end"]
            )
            for selected_match in selected_matches
        )

        if not overlaps:
            selected_matches.append(
                candidate_match
            )

    unique_surfaces = []

    for selected_match in selected_matches:
        surface = selected_match["surface"]

        if surface not in unique_surfaces:
            unique_surfaces.append(surface)

    return unique_surfaces


def plain_numeric_text(
    value: int | float,
) -> str:
    decimal_value = Decimal(str(value))

    if (
        decimal_value
        == decimal_value.to_integral()
    ):
        return format(
            decimal_value.quantize(
                Decimal("1")
            ),
            "f",
        )

    result = format(
        decimal_value.normalize(),
        "f",
    )

    if "." in result:
        result = (
            result
            .rstrip("0")
            .rstrip(".")
        )

    return result


def extract_visible_excel_literal(
    format_segment: str,
) -> str:
    visible_parts = []

    # Quoted literals such as "$"
    visible_parts.extend(
        re.findall(
            r'"([^"]*)"',
            format_segment,
        )
    )

    # Escaped literal characters
    visible_parts.extend(
        re.findall(
            r"\\([^0#?,.;_\-*])",
            format_segment,
        )
    )

    for symbol in [
        "$",
        "€",
        "£",
        "¥",
    ]:
        if (
            symbol in format_segment
            and not any(
                symbol in part
                for part in visible_parts
            )
        ):
            visible_parts.append(symbol)

    return "".join(visible_parts)


def reconstruct_numeric_display(
    value: int | float,
    number_format: str,
) -> str:
    """
    Reconstruct the visible Excel representation strictly from
    the stored numeric value and the cell number format.
    """

    plain_value = plain_numeric_text(value)

    if not isinstance(number_format, str):
        return plain_value

    format_code = number_format.strip()

    if (
        format_code == ""
        or format_code.casefold() == "general"
    ):
        return plain_value

    positive_section = (
        format_code
        .split(";")[0]
        .strip()
    )

    if "%" in positive_section:
        percentage_value = (
            Decimal(str(value))
            * Decimal("100")
        )

        decimal_match = re.search(
            r"\.([0#]+)",
            positive_section,
        )

        decimal_places = (
            len(decimal_match.group(1))
            if decimal_match
            else 0
        )

        return (
            f"{percentage_value:.{decimal_places}f}"
            "%"
        )

    placeholder_positions = [
        position
        for position, character
        in enumerate(positive_section)
        if character in {
            "0",
            "#",
            "?",
        }
    ]

    if not placeholder_positions:
        return plain_value

    first_placeholder = min(
        placeholder_positions
    )

    last_placeholder = max(
        placeholder_positions
    )

    prefix_segment = positive_section[
        :first_placeholder
    ]

    numeric_segment = positive_section[
        first_placeholder:
        last_placeholder + 1
    ]

    suffix_segment = positive_section[
        last_placeholder + 1:
    ]

    prefix = extract_visible_excel_literal(
        prefix_segment
    )

    suffix = extract_visible_excel_literal(
        suffix_segment
    )

    use_grouping = "," in numeric_segment

    decimal_match = re.search(
        r"\.([0#]+)",
        numeric_segment,
    )

    decimal_places = (
        len(decimal_match.group(1))
        if decimal_match
        else 0
    )

    decimal_value = Decimal(str(value))

    if use_grouping:
        formatted_number = format(
            decimal_value,
            f",.{decimal_places}f",
        )
    else:
        formatted_number = format(
            decimal_value,
            f".{decimal_places}f",
        )

    if decimal_places == 0:
        formatted_number = (
            formatted_number
            .split(".")[0]
        )

    return (
        f"{prefix}"
        f"{formatted_number}"
        f"{suffix}"
    )


# Obtain the original normalizer even when this Patch cell
# is accidentally executed more than once.
_base_normalizer = getattr(
    normalize_model_output_cell,
    "_base_normalizer",
    normalize_model_output_cell,
)


def normalize_model_output_cell_final(
    *,
    raw_value: Any,
    number_format: str,
    document_text: str,
    workbook_epoch: Any,
) -> dict[str, Any]:
    result = _base_normalizer(
        raw_value=raw_value,
        number_format=number_format,
        document_text=document_text,
        workbook_epoch=workbook_epoch,
    )

    # --------------------------------------------------------
    # Correct time normalization
    # --------------------------------------------------------

    if (
        result["source_value_category"]
        == "excel_time"
    ):
        time_value = raw_value

        if (
            isinstance(
                time_value,
                (int, float),
            )
            and not isinstance(
                time_value,
                bool,
            )
            and isinstance(
                number_format,
                str,
            )
            and is_date_format(
                number_format
            )
        ):
            time_value = from_excel(
                time_value,
                epoch=workbook_epoch,
            )

        if isinstance(
            time_value,
            datetime,
        ):
            time_value = time_value.time()

        if not isinstance(
            time_value,
            time,
        ):
            raise TypeError(
                "An Excel time output could not be "
                "recovered as a Python time value."
            )

        matches = (
            strict_document_surface_matches(
                time_surface_candidates(
                    time_value
                ),
                document_text,
            )
        )

        if len(matches) == 1:
            result["answer"] = matches[0]
            result["normalization_status"] = (
                "TIME_RESOLVED_FROM_DOCUMENT"
            )

        elif len(matches) > 1:
            result["answer"] = (
                canonical_time_text(
                    time_value
                )
            )

            result["normalization_status"] = (
                "TIME_MULTIPLE_DOCUMENT_SURFACES_"
                "CANONICALIZED"
            )

        else:
            result["answer"] = (
                canonical_time_text(
                    time_value
                )
            )

            result["normalization_status"] = (
                "TIME_NO_DOCUMENT_SURFACE_"
                "CANONICALIZED"
            )

        result["document_surface_match"] = (
            len(matches) > 0
        )

        result["surface_match_count"] = (
            len(matches)
        )

    # --------------------------------------------------------
    # Correct numeric display reconstruction
    # --------------------------------------------------------

    elif (
        result["source_value_category"]
        == "numeric"
    ):
        reconstructed_answer = (
            reconstruct_numeric_display(
                raw_value,
                number_format,
            )
        )

        unformatted_answer = (
            plain_numeric_text(
                raw_value
            )
        )

        result["answer"] = (
            reconstructed_answer
        )

        result["document_surface_match"] = (
            canonical_casefold(
                reconstructed_answer
            )
            in canonical_casefold(
                document_text
            )
        )

        if (
            reconstructed_answer
            != unformatted_answer
        ):
            result["normalization_status"] = (
                "NUMERIC_DISPLAY_RECONSTRUCTED"
            )
        else:
            result["normalization_status"] = (
                "NUMERIC_VALUE_PRESERVED"
            )

    return result


normalize_model_output_cell_final._base_normalizer = (
    _base_normalizer
)

normalize_model_output_cell_final._patch_version = (
    NORMALIZATION_PATCH_VERSION
)

normalize_model_output_cell = (
    normalize_model_output_cell_final
)


print(
    "Final normalization Patch active:",
    normalize_model_output_cell._patch_version,
)

Final normalization Patch active: 2.1.0-final

In [10]:
# Cell 10

model_prompt_counts = (
    normalized_outputs
    .groupby(
        [
            "model",
            "prompt",
        ]
    )
    .size()
    .rename("rows")
    .reset_index()
)

id_counts = (
    normalized_outputs
    .groupby("id")
    .size()
)

missing_outputs = normalized_outputs[
    normalized_outputs[
        "output_missing"
    ]
].copy()

print(
    f"Rows                    : "
    f"{len(normalized_outputs)}"
)

print(
    f"Unique experiment keys  : "
    f"{normalized_outputs['experiment_key'].nunique()}"
)

print(
    f"Unique benchmark IDs    : "
    f"{normalized_outputs['id'].nunique()}"
)

print(
    f"Detected models         : "
    f"{normalized_outputs['model'].nunique()}"
)

print(
    f"Detected prompts        : "
    f"{normalized_outputs['prompt'].nunique()}"
)

print(
    f"Missing outputs         : "
    f"{len(missing_outputs)}"
)

display(
    model_prompt_counts
)

if len(normalized_outputs) != 6000:
    raise RuntimeError(
        "The normalized output dataset does not "
        "contain 6,000 rows."
    )

if (
    normalized_outputs[
        "experiment_key"
    ].nunique()
    != 6000
):
    raise RuntimeError(
        "Experiment keys are not unique."
    )

if not id_counts.eq(20).all():
    raise RuntimeError(
        "Each benchmark ID must have exactly "
        "20 Model–Prompt outputs."
    )

if not model_prompt_counts[
    "rows"
].eq(300).all():
    raise RuntimeError(
        "Each Model–Prompt combination must "
        "contain 300 rows."
    )

if (
    normalized_outputs[
        "model"
    ].nunique()
    != 4
):
    raise RuntimeError(
        "The normalized output dataset does not "
        "contain four models."
    )

if set(
    normalized_outputs[
        "prompt"
    ].unique()
) != set(PROMPT_LABELS):
    raise RuntimeError(
        "The normalized output dataset contains "
        "unexpected Prompt labels."
    )

if len(missing_outputs) != 9:
    raise RuntimeError(
        "The number of missing outputs differs "
        "from the verified source count of 9."
    )

print("Long-format experiment matrix validation passed.")

Rows                    : 6000
Unique experiment keys  : 6000
Unique benchmark IDs    : 300
Detected models         : 4
Detected prompts        : 5
Missing outputs         : 9

                model prompt  rows
0     DeepSeek V4 Pro      A   300
1     DeepSeek V4 Pro      B   300
2     DeepSeek V4 Pro      C   300
3     DeepSeek V4 Pro     C1   300
4     DeepSeek V4 Pro     C2   300
5      Gemini 3.1 Pro      A   300
6      Gemini 3.1 Pro      B   300
7      Gemini 3.1 Pro      C   300
8      Gemini 3.1 Pro     C1   300
9      Gemini 3.1 Pro     C2   300
10  claude 4.6 Sonnet      A   300
11  claude 4.6 Sonnet      B   300
12  claude 4.6 Sonnet      C   300
13  claude 4.6 Sonnet     C1   300
14  claude 4.6 Sonnet     C2   300
15            gpt 5.4      A   300
16            gpt 5.4      B   300
17            gpt 5.4      C   300
18            gpt 5.4     C1   300
19            gpt 5.4     C2   300

Long-format experiment matrix validation passed.

In [11]:
# Cell 11

output_type_summary = (
    normalized_outputs
    .groupby(
        [
            "source_value_category",
            "normalization_status",
        ],
        dropna=False,
    )
    .size()
    .rename("count")
    .reset_index()
    .sort_values(
        [
            "source_value_category",
            "normalization_status",
        ]
    )
    .reset_index(drop=True)
)

date_time_output_audit = normalized_outputs[
    normalized_outputs[
        "source_value_category"
    ].isin(
        [
            "excel_date",
            "excel_datetime",
            "excel_time",
        ]
    )
].copy()

numeric_output_audit = normalized_outputs[
    normalized_outputs[
        "source_value_category"
    ].eq("numeric")
].copy()

prompt_warning_outputs = normalized_outputs[
    normalized_outputs[
        "prompt_audit_issue"
    ].ne("")
].copy()

display(
    output_type_summary
)

print(
    f"Date/time-valued outputs: "
    f"{len(date_time_output_audit)}"
)

print(
    f"Numeric outputs         : "
    f"{len(numeric_output_audit)}"
)

print(
    f"Missing outputs         : "
    f"{len(missing_outputs)}"
)

print(
    f"Rows linked to Prompt warnings: "
    f"{len(prompt_warning_outputs)}"
)

if not date_time_output_audit.empty:
    display(
        date_time_output_audit[
            [
                "id",
                "model",
                "prompt",
                "raw_value_repr",
                "answer",
                "normalization_status",
                "document_surface_match",
                "source_number_format",
            ]
        ].head(25)
    )

  source_value_category           normalization_status  count
0            excel_date    DATE_RESOLVED_FROM_DOCUMENT   1381
1            excel_time    TIME_RESOLVED_FROM_DOCUMENT     39
2               missing                 MISSING_OUTPUT      9
3               numeric  NUMERIC_DISPLAY_RECONSTRUCTED     14
4               numeric        NUMERIC_VALUE_PRESERVED      1
5                  text                TEXT_NORMALIZED   4556

Date/time-valued outputs: 1420
Numeric outputs         : 15
Missing outputs         : 9
Rows linked to Prompt warnings: 68

,id,model,prompt,raw_value_repr,answer,normalization_status,document_surface_match,source_number_format
1,1,DeepSeek V4 Pro,B,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
3,1,DeepSeek V4 Pro,C1,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
4,1,DeepSeek V4 Pro,C2,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
6,1,Gemini 3.1 Pro,B,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
7,1,Gemini 3.1 Pro,C,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
8,1,Gemini 3.1 Pro,C1,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
9,1,Gemini 3.1 Pro,C2,"datetime.datetime(2024, 3, 12, 0, 0)",12 March 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
62,4,DeepSeek V4 Pro,C,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
63,4,DeepSeek V4 Pro,C1,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
66,4,Gemini 3.1 Pro,B,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
67,4,Gemini 3.1 Pro,C,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
68,4,Gemini 3.1 Pro,C1,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
69,4,Gemini 3.1 Pro,C2,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
70,4,claude 4.6 Sonnet,A,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
71,4,claude 4.6 Sonnet,B,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
72,4,claude 4.6 Sonnet,C,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
73,4,claude 4.6 Sonnet,C1,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
74,4,claude 4.6 Sonnet,C2,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
79,4,gpt 5.4,C2,"datetime.datetime(2024, 2, 22, 0, 0)",22 February 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
121,7,DeepSeek V4 Pro,B,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
122,7,DeepSeek V4 Pro,C,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
123,7,DeepSeek V4 Pro,C1,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
124,7,DeepSeek V4 Pro,C2,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
126,7,Gemini 3.1 Pro,B,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy
127,7,Gemini 3.1 Pro,C,"datetime.datetime(2024, 4, 5, 0, 0)",5 April 2024,DATE_RESOLVED_FROM_DOCUMENT,True,d-mmm-yy

In [12]:
# Cell 12

missing_with_nonempty_answer = (
    normalized_outputs[
        normalized_outputs[
            "output_missing"
        ]
        & normalized_outputs[
            "answer"
        ].ne("")
    ]
)

nonmissing_with_empty_answer = (
    normalized_outputs[
        ~normalized_outputs[
            "output_missing"
        ]
        & normalized_outputs[
            "answer"
        ].eq("")
    ]
)

date_outputs_with_timestamp_suffix = (
    normalized_outputs[
        normalized_outputs[
            "source_value_category"
        ].eq("excel_date")
        & normalized_outputs[
            "answer"
        ].str.contains(
            r"00:00:00",
            regex=True,
            na=False,
        )
    ]
)

invalid_missing_literals = (
    normalized_outputs[
        normalized_outputs[
            "answer"
        ].str.casefold().isin(
            [
                "nan",
                "nat",
                "none",
                "<na>",
            ]
        )
    ]
)

invalid_normalization_status = (
    normalized_outputs[
        normalized_outputs[
            "normalization_status"
        ].isna()
    ]
)

normalization_validation_rows = [
    {
        "Check": "Normalized rows",
        "Observed": len(normalized_outputs),
        "Expected": 6000,
        "Status": (
            "PASS"
            if len(normalized_outputs) == 6000
            else "FAIL"
        ),
    },
    {
        "Check": "Unique experiment keys",
        "Observed": (
            normalized_outputs[
                "experiment_key"
            ].nunique()
        ),
        "Expected": 6000,
        "Status": (
            "PASS"
            if normalized_outputs[
                "experiment_key"
            ].nunique() == 6000
            else "FAIL"
        ),
    },
    {
        "Check": "Missing outputs",
        "Observed": len(missing_outputs),
        "Expected": 9,
        "Status": (
            "PASS"
            if len(missing_outputs) == 9
            else "FAIL"
        ),
    },
    {
        "Check": "Missing outputs with nonempty answer",
        "Observed": len(
            missing_with_nonempty_answer
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                missing_with_nonempty_answer
            ) == 0
            else "FAIL"
        ),
    },
    {
        "Check": "Nonmissing outputs with empty answer",
        "Observed": len(
            nonmissing_with_empty_answer
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                nonmissing_with_empty_answer
            ) == 0
            else "FAIL"
        ),
    },
    {
        "Check": "Date outputs containing 00:00:00",
        "Observed": len(
            date_outputs_with_timestamp_suffix
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                date_outputs_with_timestamp_suffix
            ) == 0
            else "FAIL"
        ),
    },
    {
        "Check": "Invalid missing-value literals",
        "Observed": len(
            invalid_missing_literals
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                invalid_missing_literals
            ) == 0
            else "FAIL"
        ),
    },
    {
        "Check": "Missing normalization statuses",
        "Observed": len(
            invalid_normalization_status
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                invalid_normalization_status
            ) == 0
            else "FAIL"
        ),
    },
]

normalization_validation = pd.DataFrame(
    normalization_validation_rows
)

display(
    normalization_validation
)

if normalization_validation[
    "Status"
].eq("FAIL").any():
    raise RuntimeError(
        "Output normalization validation failed."
    )

print("Output normalization quality checks passed.")

                                  Check  Observed  Expected Status
0                       Normalized rows      6000      6000   PASS
1                Unique experiment keys      6000      6000   PASS
2                       Missing outputs         9         9   PASS
3  Missing outputs with nonempty answer         0         0   PASS
4  Nonmissing outputs with empty answer         0         0   PASS
5      Date outputs containing 00:00:00         0         0   PASS
6        Invalid missing-value literals         0         0   PASS
7        Missing normalization statuses         0         0   PASS

Output normalization quality checks passed.

In [13]:
# Cell 13 

evaluation_v1 = pd.read_excel(
    EVALUATION_V1_PATH,
)

required_v1_columns = [
    "id",
    "model",
    "prompt",
    "answer",
]

missing_v1_columns = sorted(
    set(required_v1_columns)
    - set(evaluation_v1.columns)
)

if missing_v1_columns:
    raise ValueError(
        "Version 1 evaluation dataset is missing columns: "
        + ", ".join(missing_v1_columns)
    )

evaluation_v1 = evaluation_v1[
    required_v1_columns
].copy()

evaluation_v1["id"] = pd.to_numeric(
    evaluation_v1["id"],
    errors="raise",
).astype(int)

evaluation_v1["model"] = (
    evaluation_v1["model"]
    .astype(str)
    .str.strip()
)

evaluation_v1["prompt"] = (
    evaluation_v1["prompt"]
    .astype(str)
    .str.strip()
)


def normalize_v1_comparison_value(
    value: Any,
) -> str:
    if is_missing_value(value):
        return ""

    if isinstance(value, datetime):
        return (
            value
            .replace(microsecond=0)
            .isoformat(sep=" ")
        )

    if isinstance(value, date):
        return value.isoformat()

    if isinstance(value, time):
        return canonical_time_text(
            value
        )

    return normalize_whitespace(
        value
    )


evaluation_v1["answer_v1"] = (
    evaluation_v1["answer"]
    .map(
        normalize_v1_comparison_value
    )
)

evaluation_v1 = evaluation_v1.drop(
    columns=["answer"]
)

if len(evaluation_v1) != 6000:
    raise RuntimeError(
        "Version 1 evaluation dataset does not "
        "contain 6,000 rows."
    )

if evaluation_v1.duplicated(
    subset=[
        "id",
        "model",
        "prompt",
    ]
).any():
    raise RuntimeError(
        "Version 1 evaluation keys are not unique."
    )

comparison = normalized_outputs.merge(
    evaluation_v1,
    on=[
        "id",
        "model",
        "prompt",
    ],
    how="left",
    validate="one_to_one",
)

if comparison[
    "answer_v1"
].isna().any():
    raise RuntimeError(
        "Some Version 2 rows could not be matched "
        "to the Version 1 evaluation dataset."
    )

comparison["answer_changed"] = (
    comparison["answer"]
    != comparison["answer_v1"]
)

changed_output_comparison = comparison[
    comparison["answer_changed"]
].copy()

comparison_summary = (
    comparison
    .groupby(
        "source_value_category",
        dropna=False,
    )
    .agg(
        rows=(
            "experiment_key",
            "size",
        ),
        answers_changed=(
            "answer_changed",
            "sum",
        ),
    )
    .reset_index()
)

comparison_summary[
    "change_percentage"
] = (
    comparison_summary[
        "answers_changed"
    ]
    / comparison_summary["rows"]
    * 100
).round(4)

display(
    comparison_summary
)

print(
    "Answers changed by normalization: "
    f"{len(changed_output_comparison)}"
)

if not changed_output_comparison.empty:
    display(
        changed_output_comparison[
            [
                "id",
                "model",
                "prompt",
                "source_value_category",
                "raw_value_repr",
                "answer_v1",
                "answer",
                "normalization_status",
            ]
        ].head(30)
    )

  source_value_category  rows  answers_changed  change_percentage
0            excel_date  1381             1381           100.0000
1            excel_time    39               39           100.0000
2               missing     9                0             0.0000
3               numeric    15               14            93.3333
4                  text  4556                0             0.0000

Answers changed by normalization: 1434

,id,model,prompt,source_value_category,raw_value_repr,answer_v1,answer,normalization_status
1,1,DeepSeek V4 Pro,B,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
3,1,DeepSeek V4 Pro,C1,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
4,1,DeepSeek V4 Pro,C2,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
6,1,Gemini 3.1 Pro,B,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
7,1,Gemini 3.1 Pro,C,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
8,1,Gemini 3.1 Pro,C1,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
9,1,Gemini 3.1 Pro,C2,excel_date,"datetime.datetime(2024, 3, 12, 0, 0)",2024-03-12 00:00:00,12 March 2024,DATE_RESOLVED_FROM_DOCUMENT
62,4,DeepSeek V4 Pro,C,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
63,4,DeepSeek V4 Pro,C1,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
66,4,Gemini 3.1 Pro,B,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
67,4,Gemini 3.1 Pro,C,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
68,4,Gemini 3.1 Pro,C1,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
69,4,Gemini 3.1 Pro,C2,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
70,4,claude 4.6 Sonnet,A,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
71,4,claude 4.6 Sonnet,B,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
72,4,claude 4.6 Sonnet,C,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
73,4,claude 4.6 Sonnet,C1,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
74,4,claude 4.6 Sonnet,C2,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
79,4,gpt 5.4,C2,excel_date,"datetime.datetime(2024, 2, 22, 0, 0)",2024-02-22 00:00:00,22 February 2024,DATE_RESOLVED_FROM_DOCUMENT
121,7,DeepSeek V4 Pro,B,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
122,7,DeepSeek V4 Pro,C,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
123,7,DeepSeek V4 Pro,C1,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
124,7,DeepSeek V4 Pro,C2,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
126,7,Gemini 3.1 Pro,B,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
127,7,Gemini 3.1 Pro,C,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
128,7,Gemini 3.1 Pro,C1,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
129,7,Gemini 3.1 Pro,C2,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
131,7,claude 4.6 Sonnet,B,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
132,7,claude 4.6 Sonnet,C,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT
133,7,claude 4.6 Sonnet,C1,excel_date,"datetime.datetime(2024, 4, 5, 0, 0)",2024-04-05 00:00:00,5 April 2024,DATE_RESOLVED_FROM_DOCUMENT

In [14]:
# Cell 14

analysis_dataset_columns = [
    "experiment_key",
    "id",
    "doc_id",
    "model",
    "prompt",
    "document_text",
    "question",
    "gold_answer",
    "answer",
    "answer_type",
    "injection_tag",
    "output_missing",
    "source_value_category",
    "normalization_status",
    "document_surface_match",
    "prompt_audit_issue",
]

analysis_dataset_v2 = normalized_outputs[
    analysis_dataset_columns
].copy()

analysis_dataset_v2 = (
    analysis_dataset_v2
    .sort_values(
        [
            "id",
            "model",
            "prompt",
        ]
    )
    .reset_index(drop=True)
)

required_nonmissing_metadata = [
    "experiment_key",
    "id",
    "doc_id",
    "model",
    "prompt",
    "document_text",
    "question",
    "gold_answer",
    "answer_type",
    "injection_tag",
]

metadata_missing_counts = (
    analysis_dataset_v2[
        required_nonmissing_metadata
    ]
    .isna()
    .sum()
)

if metadata_missing_counts.sum() != 0:
    display(
        metadata_missing_counts[
            metadata_missing_counts > 0
        ]
    )

    raise RuntimeError(
        "The analysis checkpoint contains missing "
        "benchmark or experiment metadata."
    )

if len(analysis_dataset_v2) != 6000:
    raise RuntimeError(
        "The analysis checkpoint does not contain "
        "6,000 rows."
    )

print("Notebook 03 input dataset created.")
print(f"Rows   : {len(analysis_dataset_v2)}")
print(f"Columns: {analysis_dataset_v2.shape[1]}")

Notebook 03 input dataset created.
Rows   : 6000
Columns: 16

In [18]:
# Cell 15

# ============================================================
# Cell 15 — Notebook 02 validation summary
# ============================================================

date_time_document_match_count = int(
    date_time_output_audit[
        "document_surface_match"
    ]
    .fillna(False)
    .astype(bool)
    .sum()
)

date_time_nonunique_surface_count = int(
    date_time_output_audit[
        "surface_match_count"
    ]
    .ne(1)
    .sum()
)


notebook02_validation_rows = [
    {
        "Check": "Source-file hash",
        "Observed": "Verified",
        "Expected": "Verified",
        "Status": "PASS",
        "Note": "",
    },

    {
        "Check": "Normalized experiment rows",
        "Observed": len(
            normalized_outputs
        ),
        "Expected": 6000,
        "Status": (
            "PASS"
            if len(normalized_outputs) == 6000
            else "FAIL"
        ),
        "Note": "",
    },

    {
        "Check": "Unique experiment keys",
        "Observed": (
            normalized_outputs[
                "experiment_key"
            ].nunique()
        ),
        "Expected": 6000,
        "Status": (
            "PASS"
            if normalized_outputs[
                "experiment_key"
            ].nunique() == 6000
            else "FAIL"
        ),
        "Note": "",
    },

    {
        "Check": "Model–Prompt cells",
        "Observed": len(
            model_prompt_counts
        ),
        "Expected": 20,
        "Status": (
            "PASS"
            if len(model_prompt_counts) == 20
            else "FAIL"
        ),
        "Note": "",
    },

    {
        "Check": "Rows per Model–Prompt cell",
        "Observed": (
            "All 300"
            if model_prompt_counts[
                "rows"
            ].eq(300).all()
            else "Not balanced"
        ),
        "Expected": "All 300",
        "Status": (
            "PASS"
            if model_prompt_counts[
                "rows"
            ].eq(300).all()
            else "FAIL"
        ),
        "Note": "",
    },

    {
        "Check": "Missing model outputs",
        "Observed": len(
            missing_outputs
        ),
        "Expected": 9,
        "Status": (
            "PASS"
            if len(missing_outputs) == 9
            else "FAIL"
        ),
        "Note": (
            "Missing outputs are retained "
            "and not imputed."
        ),
    },

    {
        "Check": "Date/time-valued outputs",
        "Observed": len(
            date_time_output_audit
        ),
        "Expected": "Extracted from source",
        "Status": "PASS",
        "Note": (
            "No count was estimated or "
            "manually entered."
        ),
    },

    {
        "Check": (
            "Date/time outputs matched "
            "to document surface"
        ),
        "Observed": (
            date_time_document_match_count
        ),
        "Expected": len(
            date_time_output_audit
        ),
        "Status": (
            "PASS"
            if date_time_document_match_count
            == len(date_time_output_audit)
            else "WARN"
        ),
        "Note": (
            ""
            if date_time_document_match_count
            == len(date_time_output_audit)
            else (
                "Some date/time-valued outputs "
                "were not matched to a document "
                "surface form."
            )
        ),
    },

    {
        "Check": (
            "Date/time outputs without unique "
            "document surface"
        ),
        "Observed": (
            date_time_nonunique_surface_count
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if date_time_nonunique_surface_count == 0
            else "WARN"
        ),
        "Note": (
            ""
            if date_time_nonunique_surface_count == 0
            else (
                "Values without a unique document "
                "surface are retained canonically "
                "and are not replaced using guessed "
                "document text."
            )
        ),
    },

    {
        "Check": (
            "Date outputs containing 00:00:00"
        ),
        "Observed": len(
            date_outputs_with_timestamp_suffix
        ),
        "Expected": 0,
        "Status": (
            "PASS"
            if len(
                date_outputs_with_timestamp_suffix
            ) == 0
            else "FAIL"
        ),
        "Note": "",
    },

    {
        "Check": (
            "Prompt-anomaly-linked output rows"
        ),
        "Observed": len(
            prompt_warning_outputs
        ),
        "Expected": (
            "Documented source anomalies"
        ),
        "Status": (
            "WARN"
            if len(prompt_warning_outputs) > 0
            else "PASS"
        ),
        "Note": (
            "The executed outputs are retained "
            "without modifying the corresponding "
            "prompts."
        ),
    },

    {
        "Check": (
            "Answers changed relative to Version 1"
        ),
        "Observed": len(
            changed_output_comparison
        ),
        "Expected": (
            "Computed comparison"
        ),
        "Status": "PASS",
        "Note": (
            "Changes are caused only by the "
            "documented normalization rules."
        ),
    },
]


notebook02_validation = pd.DataFrame(
    notebook02_validation_rows
)

display(
    notebook02_validation
)


failed_notebook02_checks = (
    notebook02_validation[
        "Status"
    ].eq("FAIL")
)

if failed_notebook02_checks.any():
    display(
        notebook02_validation[
            failed_notebook02_checks
        ]
    )

    raise RuntimeError(
        "Notebook 02 contains failed "
        "validation checks."
    )


print(
    "Notebook 02 validation completed "
    "without fatal errors."
)

,Check,Observed,Expected,Status,Note
0,Source-file hash,Verified,Verified,PASS,
1,Normalized experiment rows,6000,6000,PASS,
2,Unique experiment keys,6000,6000,PASS,
3,Model–Prompt cells,20,20,PASS,
4,Rows per Model–Prompt cell,All 300,All 300,PASS,
5,Missing model outputs,9,9,PASS,Missing outputs are retained and not imputed.
6,Date/time-valued outputs,1420,Extracted from source,PASS,No count was estimated or manually entered.
7,Date/time outputs matched to document surface,1420,1420,PASS,
8,Date/time outputs without unique document surface,0,0,PASS,
9,Date outputs containing 00:00:00,0,0,PASS,
10,Prompt-anomaly-linked output rows,68,Documented source anomalies,WARN,The executed outputs are retained without modi...
11,Answers changed relative to Version 1,1434,Computed comparison,PASS,Changes are caused only by the documented norm...

Notebook 02 validation completed without fatal errors.

In [19]:
# Cell 16

analysis_parquet_path = (
    CHECKPOINT_DIR
    / "analysis_dataset_v2.parquet"
)

normalized_excel_path = (
    CHECKPOINT_DIR
    / "Normalized_Model_Outputs_v2.xlsx"
)

full_normalization_parquet_path = (
    CHECKPOINT_DIR
    / "Output_Normalization_Full_v2.parquet"
)

type_summary_path = (
    AUDIT_DIR
    / "Output_Type_Summary_v2.xlsx"
)

date_time_audit_path = (
    AUDIT_DIR
    / "Date_Time_Output_Normalization_Audit_v2.xlsx"
)

numeric_audit_path = (
    AUDIT_DIR
    / "Numeric_Output_Audit_v2.xlsx"
)

missing_output_path = (
    AUDIT_DIR
    / "Missing_Model_Outputs_v2.xlsx"
)

comparison_summary_path = (
    AUDIT_DIR
    / "Output_Normalization_Comparison_Summary_v2.xlsx"
)

changed_comparison_path = (
    AUDIT_DIR
    / "Output_Normalization_Changes_v1_vs_v2.xlsx"
)

validation_summary_path = (
    AUDIT_DIR
    / "Notebook02_Validation_Summary_v2.xlsx"
)

model_prompt_matrix_path = (
    TABLE_DIR
    / "Table13_Model_Prompt_Normalization_Matrix.xlsx"
)


analysis_dataset_v2.to_parquet(
    analysis_parquet_path,
    index=False,
    engine="pyarrow",
)

normalized_outputs.to_parquet(
    full_normalization_parquet_path,
    index=False,
    engine="pyarrow",
)

normalized_excel_columns = [
    "experiment_key",
    "id",
    "doc_id",
    "model",
    "prompt",
    "question",
    "gold_answer",
    "answer",
    "answer_type",
    "injection_tag",
    "output_missing",
    "source_value_category",
    "normalization_status",
    "prompt_audit_issue",
]

write_table(
    normalized_outputs[
        normalized_excel_columns
    ],
    normalized_excel_path,
)

write_table(
    output_type_summary,
    type_summary_path,
)

write_table(
    date_time_output_audit[
        [
            "experiment_key",
            "id",
            "doc_id",
            "model",
            "prompt",
            "question",
            "gold_answer",
            "raw_value_repr",
            "answer",
            "source_value_category",
            "normalization_status",
            "document_surface_match",
            "surface_match_count",
            "source_python_type",
            "source_number_format",
            "converted_from_excel_serial",
        ]
    ],
    date_time_audit_path,
)

write_table(
    numeric_output_audit[
        [
            "experiment_key",
            "id",
            "model",
            "prompt",
            "question",
            "gold_answer",
            "raw_value_repr",
            "answer",
            "source_number_format",
            "document_surface_match",
        ]
    ],
    numeric_audit_path,
)

write_table(
    missing_outputs[
        [
            "experiment_key",
            "id",
            "doc_id",
            "model",
            "prompt",
            "question",
            "gold_answer",
            "answer_type",
            "injection_tag",
            "normalization_status",
            "prompt_audit_issue",
        ]
    ],
    missing_output_path,
)

write_table(
    comparison_summary,
    comparison_summary_path,
)

write_table(
    changed_output_comparison[
        [
            "experiment_key",
            "id",
            "model",
            "prompt",
            "question",
            "gold_answer",
            "source_value_category",
            "raw_value_repr",
            "answer_v1",
            "answer",
            "normalization_status",
        ]
    ],
    changed_comparison_path,
)

write_table(
    notebook02_validation,
    validation_summary_path,
)

write_table(
    model_prompt_counts,
    model_prompt_matrix_path,
)

generated_notebook02_outputs = [
    analysis_parquet_path,
    normalized_excel_path,
    full_normalization_parquet_path,
    type_summary_path,
    date_time_audit_path,
    numeric_audit_path,
    missing_output_path,
    comparison_summary_path,
    changed_comparison_path,
    validation_summary_path,
    model_prompt_matrix_path,
]

for output_path in generated_notebook02_outputs:
    if not output_path.is_file():
        raise RuntimeError(
            "Expected Notebook 02 output was not created: "
            f"{output_path}"
        )

print(
    "Notebook 02 checkpoints and audit files "
    "saved successfully."
)

for output_path in generated_notebook02_outputs:
    print(
        f"- {output_path.relative_to(ROOT)}"
    )

Notebook 02 checkpoints and audit files saved successfully.
- outputs_v2\checkpoints\analysis_dataset_v2.parquet
- outputs_v2\checkpoints\Normalized_Model_Outputs_v2.xlsx
- outputs_v2\checkpoints\Output_Normalization_Full_v2.parquet
- outputs_v2\audit\Output_Type_Summary_v2.xlsx
- outputs_v2\audit\Date_Time_Output_Normalization_Audit_v2.xlsx
- outputs_v2\audit\Numeric_Output_Audit_v2.xlsx
- outputs_v2\audit\Missing_Model_Outputs_v2.xlsx
- outputs_v2\audit\Output_Normalization_Comparison_Summary_v2.xlsx
- outputs_v2\audit\Output_Normalization_Changes_v1_vs_v2.xlsx
- outputs_v2\audit\Notebook02_Validation_Summary_v2.xlsx
- outputs_v2\tables\Table13_Model_Prompt_Normalization_Matrix.xlsx

In [20]:
# Cell 17

print("=" * 76)
print("NOTEBOOK 02 V2 COMPLETED SUCCESSFULLY")
print("=" * 76)

print(
    f"Normalized rows            : "
    f"{len(normalized_outputs)}"
)

print(
    f"Models                     : "
    f"{normalized_outputs['model'].nunique()}"
)

print(
    f"Prompts                    : "
    f"{normalized_outputs['prompt'].nunique()}"
)

print(
    f"Model–Prompt cells         : "
    f"{len(model_prompt_counts)}"
)

print(
    f"Missing outputs            : "
    f"{len(missing_outputs)}"
)

print(
    f"Date/time-valued outputs   : "
    f"{len(date_time_output_audit)}"
)

print(
    f"Numeric outputs            : "
    f"{len(numeric_output_audit)}"
)

print(
    f"Date/time document matches : "
    f"{date_time_document_match_count}"
)

print(
    f"Version 1 answers changed  : "
    f"{len(changed_output_comparison)}"
)

print(
    f"Prompt-warning-linked rows : "
    f"{len(prompt_warning_outputs)}"
)

print()
print(
    "No evaluation metric was calculated."
)

print(
    "Do not continue to Notebook 03 "
    "until the normalization audits are reviewed."
)

print("=" * 76)

============================================================================
NOTEBOOK 02 V2 COMPLETED SUCCESSFULLY
============================================================================
Normalized rows            : 6000
Models                     : 4
Prompts                    : 5
Model–Prompt cells         : 20
Missing outputs            : 9
Date/time-valued outputs   : 1420
Numeric outputs            : 15
Date/time document matches : 1420
Version 1 answers changed  : 1434
Prompt-warning-linked rows : 68

No evaluation metric was calculated.
Do not continue to Notebook 03 until the normalization audits are reviewed.
============================================================================